[workspace]

members = [
  "gex-sys",
  "gex-sys/parse_mak",
  "crayfish",
  "crayfish-macros",
  "crayfish-trace-macros",
  "crayfish-examples",

  "crayfish-test/trace-test"
]

exclude = [
  "crayfish-test/build-test/"
]
