[workspace]

members = [
  "gex-sys",
  "gex-sys/gex_sys_build_parse_mak",
  "crayfish",
  "crayfish-macros",
  "crayfish-trace-macros",
  "crayfish-examples",
]

exclude = [
  "crayfish-test/build-test/",
]
