[package]
name = "build-ibv"
version = "0.1.0"
authors = ["JX Wang <jxwang92@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
crayfish = {path = "../../../crayfish", features=["net-ibv"]}
