name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable
      - name: Submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive
      - name: Build && Run tests
        run: cargo test -vv
      - name: Run examples
        run: |
          GASNET_SPAWNFN=L target/debug/examples/quick_sort 2
          GASNET_SPAWNFN=L target/debug/examples/basic_gen 2
          GASNET_SPAWNFN=L target/debug/examples/basic_collective 3 
          GASNET_SPAWNFN=L target/debug/examples/basic_collective 4
          GASNET_SPAWNFN=L target/debug/examples/basic_collective 16
          GASNET_SPAWNFN=L target/debug/examples/basic_collective 17
      - name: Install Valgrind
        run: |
          sudo apt-get update -y
          sudo apt-get install -y valgrind
      - name: Run valgrind test-mem
        run: |
          valgrind  --leak-check=full --show-leak-kinds=all env GASNET_SPAWNFN=L target/debug/examples/quick_sort 2
          valgrind  --leak-check=full --show-leak-kinds=all env GASNET_SPAWNFN=L target/debug/examples/basic_gen 2
          valgrind  --leak-check=full --show-leak-kinds=all env GASNET_SPAWNFN=L target/debug/examples/basic_collective 2

  test-build:
    name: test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable
      - name: Submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive
      - name: Install MPICH & Ibverbs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mpich libibverbs-dev
      - name: Build Ibv
        run: cd crayfish-test/build-test/build-ibv && cargo build -vv

  test-trace:
    name: test-trace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable
      - name: Submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive
      - name: Build Trace
        run: cd crayfish-test/trace-test/ && cargo build -vv
      - name: Test Trace
        run: cd crayfish-test/trace-test/ && GASNET_SPAWNFN=L cargo run 2
